"""empty message

Revision ID: 4a92bc336da1
Revises: 87428e90af56
Create Date: 2021-03-30 15:14:49.786394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a92bc336da1'
down_revision = '87428e90af56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('consumer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('face', 'consumer_id')
    # ### end Alembic commands ###
